### ISSUE TITLE
How to get access to webdriver from my own download middleware?

### ISSUE THREAD

**Issue by IIIypuk09** [brandicted/scrapy-webdriver#8]
Hi,
Thakns for your work!

I have a question how to get access to webdriver from my own download middleware? I want to take a screenshot of the page when particular information is present.

thanks,
Alexander

**Comment by ncadou** [comment]
Do you mean "download handler"? You could subclass scrapy_webdriver.download.WebdriverDownloadHandler and specify the class in settings.DOWNLOAD_HANDLERS. If you meant "spider middleware" the webdriver instance is attached to the response object, so by properly ordering settings.SPIDER_MIDDLEWARES so that scrapy-webdriver kicks in first, your middleware will have access to it.
